[project]
name = "langgraph-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.38.0",
    "ipython>=9.4.0",
    "langgraph>=0.5.3",
    "pydantic>=2.11.7",
]
